# Generated by Django 4.2.13 on 2024-06-22 02:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visual_logs", "0002_enrty"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Enrty",
            new_name="Entry",
        ),
    ]
